# Generated by Django 4.2.5 on 2023-09-28 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_date_of_birthed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_of_birthed",
            new_name="date_of_birth",
        ),
    ]
